<?php $this->headTitle('Configuration'); ?>
<div class="configuration">
  <table class="languages">
    <tbody><tr>
      <td>Something settings</td>
      <td>
        <div class="onoffswitch">
          <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitchua" checked="">
          <label class="onoffswitch-label" for="myonoffswitchua">
            <span class="onoffswitch-inner"></span>
            <span class="onoffswitch-switch"></span>
          </label>
        </div>
      </td>
    </tr>
    <tr>
      <td>Something settings</td>
      <td>
        <div class="onoffswitch">
          <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitchen">
          <label class="onoffswitch-label" for="myonoffswitchen">
            <span class="onoffswitch-inner"></span>
            <span class="onoffswitch-switch"></span>
          </label>
        </div>
      </td>
    </tr>
    <tr>
      <td>Something settings</td>
      <td>
        <div class="onoffswitch">
          <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitchru" checked="">
          <label class="onoffswitch-label" for="myonoffswitchru">
            <span class="onoffswitch-inner"></span>
            <span class="onoffswitch-switch"></span>
          </label>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>
