<?php
use Account\Plugin\AclPlugin;
use Zend\Authentication\AuthenticationService;
use Account\Entity\User;

/**
 * @var $this Zend\View\Renderer\PhpRenderer
 */
echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
      <?=$this->headTitle();?>

      <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>
      <!-- Le styles -->
      <?php echo $this->headLink(
                  [
                      'rel' => 'shortcut icon',
                      'type' => 'image/vnd.microsoft.icon',
                      'href' => $this->basePath() . '/img/favicon.ico'
                  ]
              )
                  ->prependStylesheet(
                      [
                          'rel' => 'stylesheet/less',
                          'type' => 'text/css',
                          'href' => $this->basePath('css/index.less')
                      ]
                  )
                  ->prependStylesheet($this->basePath('css/generalStyle.css'))
                  ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                  ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
      ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
        ; ?>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.1/less.min.js"></script>
        <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>

  </head>
  <body>
    <div class="container"> <!-- /container -->
      <!-- top bar -->
      <div class="top">
        <div class="siteTitle"><h2><?=$this->headTitle()->renderTitle(); ?></h2></div>
        <div class="auth">
          <?php
          $auth = new AuthenticationService();
          if ($auth->getIdentity()) {
            if (User::getUserRole($auth->getIdentity()) == 'owner') {
              echo '<div class="loginButton">';
              echo '<a href="/auth/referral/">Add referral</a>';
              echo '</div>';
            }
            echo '<div class="login">';
            echo User::getUserLogin($auth->getIdentity());
            echo '</div>';

            echo '<div class="loginButton logout">';
            echo '<a href="/auth/logout/">(Logout)</a>';
            echo '</div>';
          } else {
            echo '<div class="loginButton">';
            echo '<a href="/auth/login/">Login</a> | ';
            echo '<a href="/auth/registration/">Registration</a>';
            echo '</div>';
          }
          ?>
        </div>
      </div>
      <!-- end top bar -->
      <?php
      $menuItems = [
        'dashboard',
        'reports',
        'configuration',
      ];

      echo '<menu>';
      foreach ($menuItems AS $action) {
        if ((new AclPlugin())->isAllowed($action, 'see')) {
          echo '<li>';
          echo '<a ' . (($this->action == $action) ? ' class="active"' : '') . ' href="../' . $action . '/">
                  ' . $action . '
               </a>';
          echo '</li>';
        }
      }
      echo '</menu>';
      ?>
      <div class="accessDenied">403 Access Denied</div>
    </div>  <!-- /container -->
  </body>
</html>
